services:
  - type: web
    name: vanillo
    env: node
    buildCommand: |
      npm install
      mkdir -p orders sessions
      chmod 755 orders sessions
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOW_FILE_SYSTEM
        value: "true"
    healthCheckPath: /
    autoDeploy: true 